version: '3.8'

services:
  king-11:
    image: david-11
    build: .
    ports:
      - '6005:3001'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/test'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
